#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
alias zshdir='cd ~/.zprezto/runcoms'

# Should probably investigate why I can't use the 'function'
# syntax for this.
e () {
    nohup emacsclient --alternate-editor="emacs" "$@" > /dev/null 2>&1 &
}

alias msysupdate='pacman --needed -S bash pacman msys2-runtime'
function zupdate {
    setopt EXTENDED_GLOB
    for rcfile in "${ZDOTDIR:-$HOME}"/.zprezto/runcoms/^README.md(.N); do
        rm -f "${ZDOTDIR:-$HOME}/.${rcfile:t}"
        ln -s "$rcfile" "${ZDOTDIR:-$HOME}/.${rcfile:t}"
    done
    source ~/.zprezto/runcoms/zshrc
}
