#!/usr/bin/zsh
#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#   James Brown <jamesb797@gmail.com>
#


###############
# Source Prezto
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi


#########################################
# Read further configuration from zsh.ini
configdir="$HOME/.local-config"
config="$configdir/zsh.ini"

# Ensure config dir exists
if [[ ! -d "$configdir" ]]; then
    mkdir "$configdir"
fi

# Ensure config file exists
if [[ ! -a "$config" ]]; then
    >"$config" <<EOF
[aliases]
zc=cd ~/.zprezto/runcoms
ec=cd ~/.emacs.d
lc=$configdir

[PATH]
EOF
fi

inaliases=false
inpathdef=false
while read -r line  # Can I do this without cat?
do
    if [[ "$inaliases" = true && "$line" =~ "=" ]]; then
        alias "$line"
    elif [[ "$inpathdef" = true && "$line" =~ "=" ]]; then
        export PATH=${line:2}:$PATH
    fi

    if [[ "$line" =~ "^\[aliases\]$" ]]; then
        inaliases=true
        inpathdef=false
    elif [[ "$line" =~ "^\[PATH\]$" ]]; then
        inpathdef=true
        inaliases=false
    elif [[ "$line" =~ "^\[.*\]$" ]]; then
        inaliases=false
        inpathdef=false
    fi
done <"$config"


########################################
# Ensure that the editor is set properly
export VISUAL=emacsclient
export EDITOR=emacsclient


##################
# Define utilities
alias e=e  # In Dropbox bin

alias msysupdate='pacman --needed -S bash pacman msys2-runtime'

function zupdate {
    setopt EXTENDED_GLOB
    for rcfile in "${ZDOTDIR:-$HOME}"/.zprezto/runcoms/^README.md(.N); do
        rm -f "${ZDOTDIR:-$HOME}/.${rcfile:t}"
        ln -s "$rcfile" "${ZDOTDIR:-$HOME}/.${rcfile:t}"
    done
    source ~/.zprezto/runcoms/zshrc
}
